---
- name: All logs to 111
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.rsyslog
      rsyslog_remote: 192.168.56.111
      rsyslog_remote_tcp: true
      rsyslog_remote_selector: "*.*"
      rsyslog_remote_port: 514
